apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: default
  labels:
    app: kafka-ui
data:
  KAFKA_CLUSTERS_0_NAME: "local-kafka"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-service:9092"
  DYNAMIC_CONFIG_ENABLED: "true"